[package]
name = "tofuri-bot"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Tofuri discord bot"
repository = "https://github.com/tofuri/discord-bot"

[dependencies]
tofuri-core = "0.1"
tofuri-api-core = "0.1"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.21.2", features = ["full"] }
clap = { version = "3.2.6", features = ["derive"] }
log = "0.4"
tracing-subscriber = "0.3"
reqwest = "0.11"